import { createCollabPlugin } from "@agent-native/core/server";

/**
 * Resolve the parent deck from `deck-${deckId}-slide-${slideId}` documents.
 * Slide ids generated by the agent also contain the `-slide-` marker. Using
 * the last generic marker resolves the parent deck as `<deckId>-slide` and
 * fails the access check.
 */
export function resolveDeckIdFromCollabDocId(docId: string): string {
  if (!docId.startsWith("deck-")) return docId;
  const withoutPrefix = docId.slice("deck-".length);
  // Agent-created slide ids start with `slide-`, giving us an unambiguous
  // marker even when a legacy deck id itself contains `-slide-`.
  const generatedSlideMarker = withoutPrefix.lastIndexOf("-slide-slide-");
  const slideMarker =
    generatedSlideMarker >= 0
      ? generatedSlideMarker
      : withoutPrefix.indexOf("-slide-");
  return slideMarker >= 0 ? withoutPrefix.slice(0, slideMarker) : withoutPrefix;
}

export default createCollabPlugin({
  table: "decks",
  contentColumn: "data",
  idColumn: "id",
  access: {
    mode: "resource",
    resourceType: "deck",
    resolveResourceId: resolveDeckIdFromCollabDocId,
  },
});
