/**
 * Convert a slide text object between plain lines and real UL/OL markup.
 *
 * Decks generated by the agent represent bullets as styled flex rows (see
 * `bullet-editing.ts`). Toolbar-created lists deliberately use semantic markup
 * instead, because an ordered list must renumber itself when items are added,
 * removed, or reordered, and styled rows cannot. Both shapes stay editable:
 * `RICH_BLOCK_TAGS` in SlideEditor already treats UL/OL/LI as text blocks.
 *
 * No React exports, so this stays Fast-Refresh friendly and unit-testable.
 */

import { isBulletMarker } from "./bullet-editing";

export type SlideListKind = "bullet" | "ordered";

const LIST_TAG: Record<SlideListKind, "UL" | "OL"> = {
  bullet: "UL",
  ordered: "OL",
};

/**
 * Tailwind's preflight sets `list-style: none` on every UL and OL, so the type
 * has to be restated inline or the list renders with no markers at all. The
 * marker sits outside the content box so a wrapped line aligns under its own
 * text rather than under the marker, matching how styled rows already read.
 */
const LIST_STYLE: Record<SlideListKind, string> = {
  bullet:
    "margin:0;padding-left:1.25em;list-style-position:outside;list-style-type:disc;",
  ordered:
    "margin:0;padding-left:1.25em;list-style-position:outside;list-style-type:decimal;",
};

function isListTag(element: Element): boolean {
  return element.tagName === "UL" || element.tagName === "OL";
}

/**
 * The list this object is, or the single list it wholly contains. A list
 * sitting beside other content is not something a whole-object toggle owns.
 */
function listElement(element: HTMLElement): HTMLElement | null {
  if (isListTag(element)) return element;
  const children = Array.from(element.children);
  return children.length === 1 && isListTag(children[0])
    ? (children[0] as HTMLElement)
    : null;
}

export function detectSlideListKind(
  element: HTMLElement | null,
): SlideListKind | null {
  const list = element ? listElement(element) : null;
  if (!list) return null;
  return list.tagName === "OL" ? "ordered" : "bullet";
}

/**
 * Swap an element's tag while keeping its attributes and children. UL and OL
 * differ only by tag, so switching list kind in place would otherwise leave an
 * ordered list still rendering bullets.
 */
function retag(element: HTMLElement, tagName: string): HTMLElement {
  const replacement = element.ownerDocument.createElement(tagName);
  for (const attribute of Array.from(element.attributes)) {
    replacement.setAttribute(attribute.name, attribute.value);
  }
  replacement.append(...Array.from(element.childNodes));
  element.replaceWith(replacement);
  return replacement;
}

const BLOCK_TAGS = new Set([
  "ARTICLE",
  "BLOCKQUOTE",
  "DIV",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "LI",
  "OL",
  "P",
  "PRE",
  "SECTION",
  "UL",
]);

/**
 * The object's children when it is built out of block elements, or null when
 * it holds a single run of text. Bare text or an inline tag at the top level
 * means the content is one line: treating `<strong>` as a block would keep
 * only its text and silently drop everything around it.
 */
function blockChildren(source: HTMLElement): HTMLElement[] | null {
  const blocks: HTMLElement[] = [];
  for (const node of Array.from(source.childNodes)) {
    if (node.nodeType === Node.TEXT_NODE) {
      if ((node.textContent ?? "").trim()) return null;
      continue;
    }
    if (!(node instanceof HTMLElement)) continue;
    // A break separates lines within a block run; it never makes one.
    if (node.tagName === "BR") continue;
    if (!BLOCK_TAGS.has(node.tagName)) return null;
    blocks.push(node);
  }
  return blocks.length > 0 ? blocks : null;
}

/**
 * The inner HTML of each line the object currently holds. A styled bullet row
 * contributes only its text, so converting agent-generated bullets to a real
 * list drops the now-duplicated marker instead of rendering two markers.
 */
function readLines(source: HTMLElement): string[] {
  const blocks = blockChildren(source);

  if (blocks) {
    return blocks.flatMap((block) => {
      const stripped = block.cloneNode(true) as HTMLElement;
      for (const child of Array.from(stripped.children)) {
        if (isBulletMarker(child)) child.remove();
      }
      const html = stripped.innerHTML.trim();
      return html ? [html] : [];
    });
  }

  return source.innerHTML
    .split(/<br\s*\/?>/i)
    .map((line) => line.trim())
    .filter(Boolean);
}

function itemHtml(list: HTMLElement): string[] {
  return Array.from(list.children)
    .filter((child): child is HTMLElement => child instanceof HTMLElement)
    .map((item) => item.innerHTML);
}

function buildList(
  doc: Document,
  kind: SlideListKind,
  lines: string[],
): HTMLElement {
  const list = doc.createElement(LIST_TAG[kind]);
  list.setAttribute("style", LIST_STYLE[kind]);
  for (const line of lines) {
    const item = doc.createElement("li");
    item.innerHTML = line;
    list.appendChild(item);
  }
  return list;
}

function buildLines(doc: Document, lines: string[]): DocumentFragment {
  const fragment = doc.createDocumentFragment();
  for (const line of lines) {
    const block = doc.createElement("div");
    block.innerHTML = line;
    fragment.appendChild(block);
  }
  return fragment;
}

/**
 * Toggle `element` into a list of `kind`: switching kind when it is already
 * the other one, and back to plain lines when it already matches. Returns the
 * element now holding the content, or null when there was nothing to convert
 * so the caller can skip a pointless slide write.
 */
export function toggleSlideList(
  element: HTMLElement,
  kind: SlideListKind,
): HTMLElement | null {
  const doc = element.ownerDocument;
  const existing = listElement(element);

  if (!existing) {
    const lines = readLines(element);
    if (lines.length === 0) return null;
    element.replaceChildren(buildList(doc, kind, lines));
    return element;
  }

  const lines = itemHtml(existing);

  if (existing.tagName !== LIST_TAG[kind]) {
    // Same content, different marker. The tag alone is not enough: an inline
    // `list-style-type` from the other kind would keep painting the old
    // marker, so restate it. When the object itself was the list, the retagged
    // node replaces it and is what the caller must go on using, since
    // `element` is now detached.
    const switched = retag(existing, LIST_TAG[kind]);
    switched.style.setProperty(
      "list-style-type",
      kind === "ordered" ? "decimal" : "disc",
    );
    return existing === element ? switched : element;
  }

  if (existing === element) {
    // The object itself is the list, so unwrapping means becoming a plain
    // block; its attributes (object id, position, styling) must survive.
    const unwrapped = retag(element, "DIV");
    unwrapped.replaceChildren(buildLines(doc, lines));
    unwrapped.style.removeProperty("padding-left");
    unwrapped.style.removeProperty("list-style-position");
    unwrapped.style.removeProperty("list-style-type");
    return unwrapped;
  }

  existing.replaceWith(buildLines(doc, lines));
  return element;
}
